name: Qdrant Knowledge base Ingestion

on:
  schedule:
    # Runs at 00:00 on the 1st of every month (UTC time)
    - cron: '0 0 1 * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: QDRANT KEYS
    env:
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      QDRANT_URL: ${{ secrets.QDRANT_URL }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}


    steps:
    - name: Import project files
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python ./knowledge/data_ingestion_qdrant_ci_cd.py
